[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, fzf#vim#with_preview('right:50%', 'ctrl-p'), <bang>0)
  nnoremap <Space>f :Files<CR>
  nnoremap <Space>f :FZF<CR>
  nnoremap <Space>b :Buffers<CR>
  command! -bang -nargs=? -complete=dir GFiles
    \ call fzf#vim#gitfiles(<q-args>, fzf#vim#with_preview(), <bang>0)
  nnoremap <C-i> :GFiles<CR>
  nnoremap <C-s> :GFiles?<CR>
  command! -bang -nargs=* Ag
    \ call fzf#vim#ag(<q-args>,
    \                 <bang>0 ? fzf#vim#with_preview('up:60%')
    \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
    \                 <bang>0)
  nnoremap <C-g> :Ag<Space>
  nnoremap <Space>g :exec ‘Ag’ expand(‘<cword>’)<CR>
'''

# colorscheme
[[plugins]]
repo = 'tomasiser/vim-code-dark'

[[plugins]]
repo = 'leafgarland/typescript-vim'
hook_add = '''
 let g:typescript_indent_disable = 1
'''
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

# git 
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
  set updatetime=1000
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  command Gst :Gstatus
  command Gdf :Gdiff
  command Gbl :Gblame
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline#extensions#tabline#enabled = 1
  nnoremap <C-p> :bnext<CR>
  nnoremap <C-n> :bprevious<CR>
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
  nmap gc gcc
'''
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
  let g:rainbow_active = 1
'''

[[pllugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'matze/vim-move'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'kannokanno/previm'

#tex
[[plugins]]
repo = 'lervag/vimtex'
hook_add = '''
  let g:vimtex_view_method='skim'
  let g:tex_conceal = ''
  let g:vimtex_compiler_progname='nvr'
  let g:vimtex_fold_envs = 0
  let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
  let g:vimtex_view_general_options = '@line @pdf @tex'
  let g:vimtex_compiler_latexmk = {
      \ 'background' : 1,
      \ 'build_dir' : '',
      \ 'callback' : 0,
      \ 'continuous' : 1,
      \ 'executable' : 'latexmk',
      \ 'options' : [],
      \}
'''

on_ft = ['tex']

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_start_key = '<C-q>'
'''
